#!/bin/bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
source "$ROOT_DIR/scripts/entrypoints/_python_env.sh"

export PM15MIN_PROJECT_DIR="$ROOT_DIR"
export PM15MIN_MANAGED_PROXY_ENABLE="${PM15MIN_MANAGED_PROXY_ENABLE:-1}"
pm15min_load_project_env
pm15min_load_managed_proxy_env
pm15min_activate_python

export PYTHONPATH="$ROOT_DIR/src"
export MPLCONFIGDIR="${MPLCONFIGDIR:-/tmp/pm15min-mpl}"
export PM15MIN_BACKTEST_RUNTIME_CACHE_MAX_ENTRIES="${PM15MIN_BACKTEST_RUNTIME_CACHE_MAX_ENTRIES:-0}"
export PM15MIN_BACKTEST_SURFACE_RUNTIME_CACHE_MAX_ENTRIES="${PM15MIN_BACKTEST_SURFACE_RUNTIME_CACHE_MAX_ENTRIES:-0}"
export PM15MIN_MEMORY_GUARD_ENABLE="${PM15MIN_MEMORY_GUARD_ENABLE:-1}"
export PM15MIN_MIN_AVAILABLE_MEM_GB="${PM15MIN_MIN_AVAILABLE_MEM_GB:-1}"
export PM15MIN_MEMORY_GUARD_SLEEP_SEC="${PM15MIN_MEMORY_GUARD_SLEEP_SEC:-30}"
export PM15MIN_MEMORY_GUARD_MAX_WAIT_SEC="${PM15MIN_MEMORY_GUARD_MAX_WAIT_SEC:-0}"
export PM15MIN_MODEL_BUNDLE_COPY_DIAGNOSTICS="${PM15MIN_MODEL_BUNDLE_COPY_DIAGNOSTICS:-0}"
export PM15MIN_QUICK_SCREEN_ARTIFACT_RETENTION="${PM15MIN_QUICK_SCREEN_ARTIFACT_RETENTION:-compact_rejects}"
export PM15MIN_QUICK_SCREEN_RETAIN_MIN_TRADES="${PM15MIN_QUICK_SCREEN_RETAIN_MIN_TRADES:-56}"
export PM15MIN_QUICK_SCREEN_CLEAN_FEATURE_FRAMES="${PM15MIN_QUICK_SCREEN_CLEAN_FEATURE_FRAMES:-1}"
export PM15MIN_QUICK_SCREEN_CLEAN_TRAINING_SETS="${PM15MIN_QUICK_SCREEN_CLEAN_TRAINING_SETS:-1}"

if [[ -z "${PM15MIN_EXPERIMENT_CPU_THREADS:-}" ]]; then
  cpu_count=1
  if command -v nproc >/dev/null 2>&1; then
    cpu_count="$(nproc)"
  elif command -v getconf >/dev/null 2>&1; then
    cpu_count="$(getconf _NPROCESSORS_ONLN 2>/dev/null || true)"
  fi
  if [[ ! "$cpu_count" =~ ^[0-9]+$ ]] || [[ "$cpu_count" -lt 1 ]]; then
    cpu_count=1
  fi
  expected_concurrency="${PM15MIN_EXPECTED_EXPERIMENT_CONCURRENCY:-10}"
  if [[ ! "$expected_concurrency" =~ ^[0-9]+$ ]] || [[ "$expected_concurrency" -lt 1 ]]; then
    expected_concurrency=10
  fi
  export PM15MIN_EXPERIMENT_CPU_THREADS="$(( cpu_count / expected_concurrency ))"
  if [[ "$PM15MIN_EXPERIMENT_CPU_THREADS" -lt 1 ]]; then
    export PM15MIN_EXPERIMENT_CPU_THREADS=1
  fi
fi

export OMP_NUM_THREADS="${OMP_NUM_THREADS:-$PM15MIN_EXPERIMENT_CPU_THREADS}"
export OPENBLAS_NUM_THREADS="${OPENBLAS_NUM_THREADS:-$PM15MIN_EXPERIMENT_CPU_THREADS}"
export MKL_NUM_THREADS="${MKL_NUM_THREADS:-$PM15MIN_EXPERIMENT_CPU_THREADS}"
export NUMEXPR_NUM_THREADS="${NUMEXPR_NUM_THREADS:-$PM15MIN_EXPERIMENT_CPU_THREADS}"
export GOTO_NUM_THREADS="${GOTO_NUM_THREADS:-$PM15MIN_EXPERIMENT_CPU_THREADS}"
export BLIS_NUM_THREADS="${BLIS_NUM_THREADS:-$PM15MIN_EXPERIMENT_CPU_THREADS}"
export VECLIB_MAXIMUM_THREADS="${VECLIB_MAXIMUM_THREADS:-$PM15MIN_EXPERIMENT_CPU_THREADS}"
export MALLOC_ARENA_MAX="${MALLOC_ARENA_MAX:-2}"
export PYTHONMALLOC="${PYTHONMALLOC:-malloc}"

mkdir -p "$MPLCONFIGDIR"

SCRIPT_PATH="${PM15MIN_QUICK_SCREEN_BATCH_SCRIPT:-$ROOT_DIR/scripts/research/run_quick_screen_queue_batch.py}"
exec "$PYTHON_BIN" "$SCRIPT_PATH" "$@"
