#!/bin/bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
export PROGRAM_PATH="${PROGRAM_PATH:-$ROOT_DIR/auto_research/program_reversal_dense.md}"
export SESSION_DIR="${SESSION_DIR:-$ROOT_DIR/sessions/deep_otm_baseline_reversal_dense_autoresearch}"
export AUTORUN_DIR="${AUTORUN_DIR:-$ROOT_DIR/var/research/autorun/reversal_dense}"
export CODEX_OFFICIAL_AUTH_PATH="${CODEX_OFFICIAL_AUTH_PATH:-$ROOT_DIR/var/research/autorun/codex-official-auth.json}"
export CODEX_NETWORK_PROXY_MODE="${CODEX_NETWORK_PROXY_MODE:-direct}"
export CODEX_OFFICIAL_NETWORK_PROXY_MODE="${CODEX_OFFICIAL_NETWORK_PROXY_MODE:-managed}"
export CODEX_OFFICIAL_PRIORITY="${CODEX_OFFICIAL_PRIORITY:-disabled}"
export MAX_LIVE_RUNS="${MAX_LIVE_RUNS:-5}"
export MAX_QUEUED_ITEMS="${MAX_QUEUED_ITEMS:-24}"
DEFAULT_TRACK_SLOT_CAPS_JSON='{"direction_dense":5,"reversal_dense":5}'
export TRACK_SLOT_CAPS_JSON="${TRACK_SLOT_CAPS_JSON:-$DEFAULT_TRACK_SLOT_CAPS_JSON}"
export PM15MIN_FIXED_TRACK_SLOT_CAPS_JSON="${PM15MIN_FIXED_TRACK_SLOT_CAPS_JSON:-$TRACK_SLOT_CAPS_JSON}"
export LOOP_SLEEP_SEC="${LOOP_SLEEP_SEC:-900}"
export CODEX_MODEL="${CODEX_MODEL:-gpt-5.5}"
export CODEX_REASONING_EFFORT="${CODEX_REASONING_EFFORT:-xhigh}"
export CODEX_PROMPT_BUDGET_MODE="${CODEX_PROMPT_BUDGET_MODE:-compact}"
export PM15MIN_MANAGED_EXPERIMENT_TRACK="${PM15MIN_MANAGED_EXPERIMENT_TRACK:-reversal_dense}"
export CODEX_ATTEMPT_TIMEOUT_SEC="${CODEX_ATTEMPT_TIMEOUT_SEC:-600}"
export CODEX_HEAVY_ANALYSIS_TIMEOUT_SEC="${CODEX_HEAVY_ANALYSIS_TIMEOUT_SEC:-1800}"
export MAX_CONSECUTIVE_FAILURES="${MAX_CONSECUTIVE_FAILURES:-12}"

exec "$ROOT_DIR/auto_research/codex_background_loop.sh" "$@"
