#!/bin/bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
REMOTE_HOST="${REMOTE_HOST:-ht66}"
REMOTE_ROOT="${REMOTE_ROOT:-/home/huatai/qigang/pm15min/v2}"
ACTION="${1:-diff}"

if [[ "$ACTION" != "diff" && "$ACTION" != "--upload" && "$ACTION" != "upload" && "$ACTION" != "--upload-rsync" && "$ACTION" != "upload-rsync" ]]; then
  cat >&2 <<'EOF'
usage:
  scripts/maintenance/compare_hashes_ht66.sh
  scripts/maintenance/compare_hashes_ht66.sh --upload
  scripts/maintenance/compare_hashes_ht66.sh --upload-rsync

env:
  REMOTE_HOST=ht66
  REMOTE_ROOT=/home/huatai/qigang/pm15min/v2
EOF
  exit 2
fi

TMP_DIR="$(mktemp -d)"
cleanup() {
  rm -rf "$TMP_DIR"
}
trap cleanup EXIT

LOCAL_MANIFEST="$TMP_DIR/local.jsonl"
REMOTE_MANIFEST="$TMP_DIR/remote.jsonl"
DIFF_PATHS="$TMP_DIR/diff-paths.txt"
UPLOAD_TARBALL="$TMP_DIR/hash-diff-upload.tar.gz"
REMOTE_MANIFEST_PATH="/tmp/pm15min-hash-local-$$.jsonl"
REMOTE_TARBALL_PATH="/tmp/pm15min-hash-diff-upload-$$.tar.gz"

cd "$ROOT_DIR"

python3 - <<'PY' "$LOCAL_MANIFEST"
from __future__ import annotations

import hashlib
import json
import subprocess
import sys
from pathlib import Path

out_path = Path(sys.argv[1])

include_roots = (
    "auto_research/",
    "scripts/",
    "src/",
    "tests/",
    "docs/",
    "research/experiments/suite_specs/",
)
include_files = {
    "pyproject.toml",
    "uv.lock",
}
exclude_files = {
    # Runtime research input generated by the remote factor-scout loop.
    "docs/DEEP_OTM_BASELINE_FACTOR_SCOUT_BACKLOG.md",
    # Runtime registry extended by remote autoresearch; never overwrite it from a local sync.
    "research/experiments/custom_feature_sets.json",
}
exclude_parts = (
    "/._",
    "/__pycache__/",
    "/.pytest_cache/",
    "/.mypy_cache/",
    "/.ruff_cache/",
    "/node_modules/",
    "/.next/",
    "/dist/",
    "/build/",
    "/htmlcov/",
)
exclude_prefixes = (
    "var/",
    "data/",
    "sessions/",
    "research/experiments/runs/",
    "research/experiments/cache/",
    "src/pm15min_v2.egg-info/",
)


def git_files(args: list[str]) -> list[str]:
    proc = subprocess.run(
        ["git", *args],
        check=True,
        stdout=subprocess.PIPE,
    )
    return [item.decode() for item in proc.stdout.split(b"\0") if item]


def keep(rel: str) -> bool:
    if rel in exclude_files:
        return False
    if rel in include_files:
        return True
    if rel.startswith(exclude_prefixes):
        return False
    rel_with_slashes = f"/{rel}"
    if any(part in rel_with_slashes for part in exclude_parts):
        return False
    return rel.startswith(include_roots)


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


tracked = git_files(["ls-files", "-z"])
untracked = git_files(["ls-files", "--others", "--exclude-standard", "-z"])
paths = sorted({rel for rel in [*tracked, *untracked] if keep(rel) and Path(rel).is_file()})

with out_path.open("w", encoding="utf-8") as fh:
    for rel in paths:
        path = Path(rel)
        stat = path.stat()
        fh.write(
            json.dumps(
                {
                    "path": rel,
                    "sha256": sha256(path),
                    "size": stat.st_size,
                },
                sort_keys=True,
            )
            + "\n"
        )
PY

scp -q "$LOCAL_MANIFEST" "$REMOTE_HOST:$REMOTE_MANIFEST_PATH"

ssh "$REMOTE_HOST" "cd '$REMOTE_ROOT' && python3 - '$REMOTE_MANIFEST_PATH'" > "$REMOTE_MANIFEST" <<'PY'
from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

manifest_path = Path(sys.argv[1])


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


try:
    rows = [json.loads(line) for line in manifest_path.read_text(encoding="utf-8").splitlines() if line.strip()]
finally:
    try:
        manifest_path.unlink()
    except FileNotFoundError:
        pass

for row in rows:
    rel = str(row.get("path") or "")
    path = Path(rel)
    if not path.exists():
        print(json.dumps({"path": rel, "status": "missing_remote"}, sort_keys=True))
        continue
    if not path.is_file():
        print(json.dumps({"path": rel, "status": "not_file_remote"}, sort_keys=True))
        continue
    stat = path.stat()
    print(
        json.dumps(
            {
                "path": rel,
                "status": "ok",
                "sha256": sha256(path),
                "size": stat.st_size,
            },
            sort_keys=True,
        )
    )
PY

python3 - <<'PY' "$LOCAL_MANIFEST" "$REMOTE_MANIFEST" "$DIFF_PATHS"
from __future__ import annotations

import json
import sys
from pathlib import Path

local_path = Path(sys.argv[1])
remote_path = Path(sys.argv[2])
diff_paths = Path(sys.argv[3])

local = {row["path"]: row for row in (json.loads(line) for line in local_path.read_text().splitlines() if line.strip())}
remote = {row["path"]: row for row in (json.loads(line) for line in remote_path.read_text().splitlines() if line.strip())}

diffs: list[dict[str, object]] = []
for rel, local_row in sorted(local.items()):
    remote_row = remote.get(rel)
    if remote_row is None:
        diffs.append({"path": rel, "status": "missing_remote_manifest", "local": local_row, "remote": {}})
        continue
    status = str(remote_row.get("status") or "")
    if status != "ok":
        diffs.append({"path": rel, "status": status, "local": local_row, "remote": remote_row})
        continue
    if local_row.get("sha256") != remote_row.get("sha256"):
        diffs.append({"path": rel, "status": "hash_diff", "local": local_row, "remote": remote_row})
    elif local_row.get("size") != remote_row.get("size"):
        diffs.append({"path": rel, "status": "size_diff_same_hash", "local": local_row, "remote": remote_row})

diff_paths.write_text("".join(f"{item['path']}\n" for item in diffs), encoding="utf-8")

print(f"local_files={len(local)}")
print(f"diff_files={len(diffs)}")
if diffs:
    print("")
    print("status\tlocal_size\tremote_size\tlocal_sha256\tremote_sha256\tpath")
    for item in diffs:
        local_row = item["local"]
        remote_row = item["remote"]
        print(
            "\t".join(
                [
                    str(item["status"]),
                    str(local_row.get("size", "")),
                    str(remote_row.get("size", "")),
                    str(local_row.get("sha256", ""))[:16],
                    str(remote_row.get("sha256", ""))[:16],
                    str(item["path"]),
                ]
            )
        )
PY

if [[ "$ACTION" == "--upload" || "$ACTION" == "upload" ]]; then
  if [[ ! -s "$DIFF_PATHS" ]]; then
    echo "No differing local files to upload."
    exit 0
  fi
  echo ""
  echo "Uploading differing files as one archive to $REMOTE_HOST:$REMOTE_ROOT ..."
  COPYFILE_DISABLE=1 tar -czf "$UPLOAD_TARBALL" -T "$DIFF_PATHS"
  scp -q "$UPLOAD_TARBALL" "$REMOTE_HOST:$REMOTE_TARBALL_PATH"
  ssh "$REMOTE_HOST" "mkdir -p '$REMOTE_ROOT' && tar -xzf '$REMOTE_TARBALL_PATH' -C '$REMOTE_ROOT' && rm -f '$REMOTE_TARBALL_PATH'"
  echo "Archive upload completed."
elif [[ "$ACTION" == "--upload-rsync" || "$ACTION" == "upload-rsync" ]]; then
  if [[ ! -s "$DIFF_PATHS" ]]; then
    echo "No differing local files to upload."
    exit 0
  fi
  echo ""
  echo "Uploading differing files with rsync to $REMOTE_HOST:$REMOTE_ROOT ..."
  rsync -av --files-from="$DIFF_PATHS" ./ "$REMOTE_HOST:$REMOTE_ROOT/"
fi
