from __future__ import annotations

from dataclasses import asdict, dataclass


@dataclass(frozen=True)
class FeatureDefinition:
    name: str
    group: str
    description: str

    def to_dict(self) -> dict[str, str]:
        return asdict(self)


_FEATURES = (
    FeatureDefinition("ret_1m", "price", "1-minute log return"),
    FeatureDefinition("ret_3m", "price", "3-minute log return"),
    FeatureDefinition("ret_5m", "price", "5-minute log return"),
    FeatureDefinition("ret_15m", "price", "15-minute log return"),
    FeatureDefinition("ret_30m", "price", "30-minute log return"),
    FeatureDefinition("ret_60m", "price", "60-minute log return"),
    FeatureDefinition("rv_30", "price", "30-minute realized volatility"),
    FeatureDefinition("rv_30_lag1", "price", "Lagged 30-minute realized volatility"),
    FeatureDefinition("ma_gap_5", "price", "Gap versus 5-period moving average"),
    FeatureDefinition("ma_gap_15", "price", "Gap versus 15-period moving average"),
    FeatureDefinition("ema_gap_12", "price", "Gap versus 12-period EMA"),
    FeatureDefinition("ma_15_slope", "price", "Slope of the 15-period moving average"),
    FeatureDefinition("bb_pos_20", "price", "Position inside 20-period Bollinger band"),
    FeatureDefinition("atr_14", "price", "14-period average true range"),
    FeatureDefinition("gk_vol_30", "price", "30-minute Garman-Klass volatility"),
    FeatureDefinition("rs_vol_30", "price", "30-minute Rogers-Satchell volatility"),
    FeatureDefinition("rr_30", "price", "30-minute realized range"),
    FeatureDefinition("macd_hist", "price", "MACD histogram"),
    FeatureDefinition("rsi_14", "price", "14-period RSI"),
    FeatureDefinition("rsi_14_lag1", "price", "Lagged 14-period RSI"),
    FeatureDefinition("median_gap_20", "price", "Gap versus 20-period rolling median"),
    FeatureDefinition("price_pos_iqr_20", "price", "Position inside 20-period interquartile range"),
    FeatureDefinition("adx_14", "price", "14-period ADX trend strength"),
    FeatureDefinition("regime_trend", "price", "Trend regime flag"),
    FeatureDefinition("hour_sin", "calendar", "Hour-of-day sine encoding"),
    FeatureDefinition("hour_cos", "calendar", "Hour-of-day cosine encoding"),
    FeatureDefinition("dow_sin", "calendar", "Day-of-week sine encoding"),
    FeatureDefinition("dow_cos", "calendar", "Day-of-week cosine encoding"),
    FeatureDefinition("bias_60", "price", "Gap versus 60-period moving average"),
    FeatureDefinition("z_ret_30m", "price", "Z-scored 30-minute return"),
    FeatureDefinition("z_ret_60m", "price", "Z-scored 60-minute return"),
    FeatureDefinition("ret_1m_lag1", "price", "Lagged 1-minute return"),
    FeatureDefinition("ret_1m_lag2", "price", "Second lag of 1-minute return"),
    FeatureDefinition("ret_5m_lag1", "price", "Lagged 5-minute return"),
    FeatureDefinition("ret_15m_lag1", "price", "Lagged 15-minute return"),
    FeatureDefinition("delta_rsi", "price", "1-step RSI delta"),
    FeatureDefinition("delta_rsi_5", "price", "5-step RSI delta"),
    FeatureDefinition("macd_z", "price", "Z-scored MACD histogram"),
    FeatureDefinition("macd_extreme", "price", "Whether MACD z-score is extreme"),
    FeatureDefinition("rsi_divergence", "price", "Short-horizon RSI divergence"),
    FeatureDefinition("momentum_agree", "price", "Whether short-horizon returns agree in sign"),
    FeatureDefinition("regime_high_vol", "price", "High-volatility regime flag"),
    FeatureDefinition("taker_buy_ratio", "volume", "Taker-buy quote share"),
    FeatureDefinition("taker_buy_ratio_z", "volume", "Z-scored taker-buy ratio"),
    FeatureDefinition("taker_buy_ratio_lag1", "volume", "Lagged taker-buy ratio"),
    FeatureDefinition("trade_intensity", "volume", "Change in trade count intensity"),
    FeatureDefinition("volume_z", "volume", "Z-scored base volume"),
    FeatureDefinition("volume_z_3", "volume", "Short-horizon rolling volume z-score"),
    FeatureDefinition("vwap_gap_20", "volume", "Gap versus 20-period VWAP"),
    FeatureDefinition("vwap_gap_60", "volume", "Gap versus 60-period VWAP"),
    FeatureDefinition("obv_z", "volume", "Z-scored on-balance volume"),
    FeatureDefinition("donch_pos_20", "volume", "Position inside 20-period Donchian channel"),
    FeatureDefinition("vol_ratio_5_60", "volume", "5/60 rolling volume ratio"),
    FeatureDefinition("vol_price_corr_15", "volume", "15-period rolling price/volume correlation"),
    FeatureDefinition("ret_from_cycle_open", "cycle", "Return from cycle open"),
    FeatureDefinition("pullback_from_cycle_high", "cycle", "Pullback from cycle high"),
    FeatureDefinition("rebound_from_cycle_low", "cycle", "Rebound from cycle low"),
    FeatureDefinition("cycle_range_pos", "cycle", "Position inside current cycle range"),
    FeatureDefinition("move_z", "cycle", "Cycle move normalized by rv_30"),
    FeatureDefinition("first_half_ret", "cycle", "Return from cycle open to the first-half anchor"),
    FeatureDefinition("second_half_ret_proxy", "cycle", "Return from the first-half anchor to now"),
    FeatureDefinition("ret_from_strike", "strike", "Return vs oracle strike"),
    FeatureDefinition("basis_bp", "strike", "Binance/oracle basis in bps"),
    FeatureDefinition("has_oracle_strike", "strike", "Whether strike price was available"),
    FeatureDefinition("has_cl_strike", "strike", "Legacy-compatible alias for strike availability"),
    FeatureDefinition("move_z_strike", "strike", "Strike return normalized by rv_30"),
    FeatureDefinition("q_bs_up_strike", "strike", "Raw BS-style strike probability proxy"),
    FeatureDefinition("q_bs_up_strike_centered", "strike", "Centered BS-style strike probability proxy"),
    FeatureDefinition("btc_ret_5m", "cross_asset", "BTC 5-minute return"),
    FeatureDefinition("btc_vol_30m", "cross_asset", "BTC 30-minute volatility"),
    FeatureDefinition("rel_strength_15m", "cross_asset", "Asset minus BTC 15-minute return"),
)

_FEATURE_SET_COLUMNS = {
    "v6_user_core": (
        "ret_1m",
        "ret_3m",
        "ret_15m",
        "rv_30",
        "atr_14",
        "adx_14",
        "regime_high_vol",
        "taker_buy_ratio",
        "taker_buy_ratio_z",
        "volume_z",
        "vwap_gap_20",
        "bias_60",
        "vol_price_corr_15",
        "volume_z_3",
        "vol_ratio_5_60",
        "ret_from_cycle_open",
        "move_z",
        "pullback_from_cycle_high",
        "rebound_from_cycle_low",
        "cycle_range_pos",
        "ret_1m_lag1",
        "ret_5m_lag1",
        "delta_rsi",
        "delta_rsi_5",
        "macd_z",
        "btc_ret_5m",
        "btc_vol_30m",
        "rel_strength_15m",
        "ret_from_strike",
        "basis_bp",
        "has_cl_strike",
    ),
    "deep_otm_v1": (
        "ret_1m",
        "ret_3m",
        "ret_5m",
        "ret_15m",
        "rv_30",
        "taker_buy_ratio",
        "taker_buy_ratio_z",
        "volume_z",
        "ret_from_cycle_open",
        "pullback_from_cycle_high",
        "rebound_from_cycle_low",
        "cycle_range_pos",
        "move_z",
        "ret_from_strike",
        "basis_bp",
        "has_oracle_strike",
        "move_z_strike",
        "q_bs_up_strike_centered",
        "btc_ret_5m",
        "btc_vol_30m",
        "rel_strength_15m",
    ),
    "alpha_search_direction_live": (
        "ret_1m",
        "ret_3m",
        "ret_5m",
        "ret_15m",
        "ret_30m",
        "ma_gap_5",
        "bb_pos_20",
        "rv_30",
        "rv_30_lag1",
        "atr_14",
        "price_pos_iqr_20",
        "adx_14",
        "regime_high_vol",
        "taker_buy_ratio",
        "taker_buy_ratio_z",
        "volume_z",
        "hour_sin",
        "hour_cos",
        "bias_60",
        "vol_price_corr_15",
        "vol_ratio_5_60",
        "z_ret_30m",
        "ret_from_cycle_open",
        "pullback_from_cycle_high",
        "rebound_from_cycle_low",
        "cycle_range_pos",
        "move_z",
        "ret_1m_lag1",
        "ret_5m_lag1",
        "delta_rsi",
        "delta_rsi_5",
        "macd_z",
        "rsi_divergence",
        "ret_from_strike",
        "basis_bp",
        "has_cl_strike",
        "q_bs_up_strike",
        "q_bs_up_strike_centered",
        "btc_ret_5m",
        "btc_vol_30m",
        "rel_strength_15m",
    ),
    "bs_q_replace_direction": (
        "ret_1m",
        "ret_3m",
        "ret_5m",
        "ret_15m",
        "ret_30m",
        "ret_60m",
        "ma_gap_5",
        "ma_gap_15",
        "ema_gap_12",
        "ma_15_slope",
        "bb_pos_20",
        "rv_30",
        "rv_30_lag1",
        "atr_14",
        "gk_vol_30",
        "rs_vol_30",
        "rr_30",
        "macd_hist",
        "rsi_14",
        "rsi_14_lag1",
        "median_gap_20",
        "price_pos_iqr_20",
        "vwap_gap_60",
        "adx_14",
        "regime_trend",
        "regime_high_vol",
        "taker_buy_ratio",
        "taker_buy_ratio_z",
        "taker_buy_ratio_lag1",
        "trade_intensity",
        "volume_z",
        "obv_z",
        "vwap_gap_20",
        "donch_pos_20",
        "hour_sin",
        "hour_cos",
        "dow_sin",
        "dow_cos",
        "bias_60",
        "vol_price_corr_15",
        "volume_z_3",
        "vol_ratio_5_60",
        "z_ret_30m",
        "z_ret_60m",
        "ret_from_cycle_open",
        "pullback_from_cycle_high",
        "rebound_from_cycle_low",
        "cycle_range_pos",
        "first_half_ret",
        "second_half_ret_proxy",
        "ret_1m_lag1",
        "ret_1m_lag2",
        "ret_5m_lag1",
        "ret_15m_lag1",
        "delta_rsi",
        "delta_rsi_5",
        "macd_z",
        "macd_extreme",
        "rsi_divergence",
        "momentum_agree",
        "ret_from_strike",
        "basis_bp",
        "has_cl_strike",
        "q_bs_up_strike",
    ),
}

_FEATURE_SET_DROP_COLUMNS = {
    "deep_otm_v1": (
        "has_cl_strike",
    ),
    "v6_user_core": (
        "has_oracle_strike",
    ),
    "alpha_search_direction_live": (
        "has_oracle_strike",
    ),
}


def feature_registry() -> dict[str, FeatureDefinition]:
    return {feature.name: feature for feature in _FEATURES}


def feature_set_columns(feature_set: str) -> tuple[str, ...]:
    key = str(feature_set).strip().lower()
    try:
        return _FEATURE_SET_COLUMNS[key]
    except KeyError as exc:
        raise ValueError(
            f"Unsupported feature_set {feature_set!r}. Expected one of: {', '.join(sorted(_FEATURE_SET_COLUMNS))}"
        ) from exc


def feature_schema(feature_set: str) -> list[dict[str, str]]:
    registry = feature_registry()
    return [registry[name].to_dict() for name in feature_set_columns(feature_set) if name in registry]


def feature_set_drop_columns(feature_set: str) -> tuple[str, ...]:
    key = str(feature_set).strip().lower()
    feature_set_columns(key)
    return _FEATURE_SET_DROP_COLUMNS.get(key, ())
